"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from decimal import Decimal, InvalidOperation
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import dotenv_values, load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_FILE = BASE_DIR / ".env"
DOTENV_VALUES = dotenv_values(ENV_FILE) if ENV_FILE.exists() else {}
load_dotenv(ENV_FILE)


def env_raw(name, default=None):
    if name in DOTENV_VALUES:
        return DOTENV_VALUES.get(name)
    value = os.environ.get(name)
    if name == "DEBUG" and isinstance(value, str) and value.strip().lower() == "release":
        return default
    return value if value is not None else default


def env_bool(name, default=False):
    value = env_raw(name)
    if value is None:
        return default
    normalized = str(value).strip().strip('"').strip("'").lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise ImproperlyConfigured(f"{name} must be a boolean value.")


def env_list(name, default=None):
    value = env_raw(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in str(value).split(",") if item.strip()]


def env_int(name, default):
    value = env_raw(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be an integer.") from exc


def env_decimal(name, default):
    value = env_raw(name, str(default))
    try:
        return Decimal(str(value))
    except (InvalidOperation, ValueError) as exc:
        raise ImproperlyConfigured(f"{name} must be a decimal value.") from exc


def env_path(name, default):
    value = env_raw(name)
    if not value:
        return default
    path = Path(value)
    if path.is_absolute():
        return path
    return BASE_DIR / path


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = env_bool("DEBUG", True)
SECRET_KEY = env_raw("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-velqaro-local-development-only"
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set when DEBUG=False.")

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    ["127.0.0.1", "localhost", "192.168.11.107"],
)
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", [])


# Application definition

INSTALLED_APPS = [
    'core',
    'products',
    'orders',
    'accounts',
    'shop',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart_counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = env_raw("DATABASE_URL", "")
if DATABASE_URL:
    try:
        import dj_database_url
    except ImportError as exc:
        raise ImproperlyConfigured("dj-database-url is required when DATABASE_URL is set.") from exc

    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=env_int("DATABASE_CONN_MAX_AGE", 600),
            conn_health_checks=env_bool("DATABASE_CONN_HEALTH_CHECKS", True),
            ssl_require=env_bool("DATABASE_SSL_REQUIRE", not DEBUG),
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Casablanca'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = env_raw("STATIC_URL", "/static/")
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = env_path("STATIC_ROOT", BASE_DIR / "staticfiles")
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
if not DEBUG:
    STORAGES["staticfiles"]["BACKEND"] = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = env_raw("MEDIA_URL", "media/")
MEDIA_ROOT = env_path("MEDIA_ROOT", BASE_DIR / "media")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

VELQARO_DELIVERY_FEE = env_decimal("VELQARO_DELIVERY_FEE", "0.00")

STORE_NAME = env_raw("STORE_NAME", "VELQARO")
STORE_TAGLINE = env_raw(
    "STORE_TAGLINE",
    "Accessoires masculins en acier 316L, livres partout au Maroc. Presence forte, details precis.",
)
STORE_META_DESCRIPTION = env_raw(
    "STORE_META_DESCRIPTION",
    "VELQARO - Accessoires masculins premium en acier 316L, livres partout au Maroc.",
)
STORE_CURRENCY_LABEL = env_raw("STORE_CURRENCY_LABEL", "DH")
STORE_FREE_DELIVERY_LABEL = env_raw("STORE_FREE_DELIVERY_LABEL", "Gratuite")
STORE_WHATSAPP_URL = env_raw("STORE_WHATSAPP_URL", "https://wa.me/212763336364")
STORE_INSTAGRAM_URL = env_raw("STORE_INSTAGRAM_URL", "https://www.instagram.com/velqaro.ma_/")
STORE_INSTAGRAM_HANDLE = env_raw("STORE_INSTAGRAM_HANDLE", "@velqaro.ma")


EMAIL_BACKEND = env_raw("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env_raw("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
EMAIL_TIMEOUT = env_int("EMAIL_TIMEOUT", 20)
EMAIL_HOST_USER = env_raw("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env_raw("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = env_raw("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
ORDER_NOTIFICATION_EMAIL = env_raw("ORDER_NOTIFICATION_EMAIL", "")

TELEGRAM_BOT_TOKEN = env_raw("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = env_raw("TELEGRAM_CHAT_ID", "")

SECURE_SSL_REDIRECT = False if DEBUG else env_bool("SECURE_SSL_REDIRECT", True)
SESSION_COOKIE_SECURE = False if DEBUG else env_bool("SESSION_COOKIE_SECURE", True)
CSRF_COOKIE_SECURE = False if DEBUG else env_bool("CSRF_COOKIE_SECURE", True)
SECURE_HSTS_SECONDS = 0 if DEBUG else env_int("SECURE_HSTS_SECONDS", 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = False if DEBUG else env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = False if DEBUG else env_bool("SECURE_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = False if DEBUG else env_bool("SECURE_CONTENT_TYPE_NOSNIFF", True)
SECURE_REFERRER_POLICY = env_raw(
    "SECURE_REFERRER_POLICY",
    "strict-origin-when-cross-origin" if not DEBUG else "same-origin",
)
X_FRAME_OPTIONS = env_raw("X_FRAME_OPTIONS", "DENY" if not DEBUG else "SAMEORIGIN")

SESSION_COOKIE_HTTPONLY = env_bool("SESSION_COOKIE_HTTPONLY", True)
CSRF_COOKIE_HTTPONLY = env_bool("CSRF_COOKIE_HTTPONLY", False)
SESSION_COOKIE_SAMESITE = env_raw("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = env_raw("CSRF_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_AGE = env_int("SESSION_COOKIE_AGE", 1209600)

if not DEBUG and env_bool("USE_X_FORWARDED_PROTO", True):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
