# Generated by Codex on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notification_email_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
