# Generated by Django 6.0.7 on 2026-08-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_notification_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_notification_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
