# Generated by Django 6.0.7 on 2026-08-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_telegram_notification_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active products are shown on the storefront. Archive a product instead of deleting it to keep historical orders intact.'),
        ),
    ]
